#!/bin/bash

echo "Edit this file and uncomment one of the curl commands to download the proper installer"

#curl -sL "https://raw.githubusercontent.com/moretticb/archlinux/x86_64-win-linux/install" > installer.sh
#curl -sL "https://raw.githubusercontent.com/moretticb/archlinux/i386_mac/install" > installer.sh

