# Maintainer: Caio Benatti Moretti
pkgbase=moretticb
pkgname=(moretticb-base)
pkgver=1
pkgrel=1
pkgdesc="Base meta package for my Arch Linux machines"
arch=(any)
url="https://github.com/moretticb/archlinux"
license=(MIT)
groups=(moretticb)

rootdir=$PWD

package_moretticb-base() {
    install=moretticb-base.install

    depends=(
        acpi
        alacritty
        termite
        adobe-source-code-pro-fonts
        adwaita-icon-theme
        alacritty
        alsa-utils
        arandr
        archlinux-keyring
        autoconf
        automake
        awesome-terminal-fonts
        baobab
        base
        bc
        beep
        bind
        binutils
        bison
        brightnessctl
        bzip2
        calc
        cantarell-fonts
        chromium
        code
        composer
        cryptsetup
        device-mapper
        dhcpcd
        diffutils
        dmenu
        docker
        docker-compose
        dosfstools
        e2fsprogs
        efibootmgr
        eog
        evince
        fakeroot
        feh
        ffmpeg
        figlet
        firefox
        flex
        fontconfig
        freetype2
        fwupd
        gcc
        git
        github-cli
        gnu-free-fonts
        go
        go-tools
        gparted
        gpick
        graphviz
        groff
        gsfonts
        gzip
        htop
        hwdata
        lxappearance
        materia-gtk-theme
        i3blocks
        i3-gaps
        i3lock
        i3status
        imagemagick
        inetutils
        intel-ucode
        ipython
        jfsutils
        jq
        jupyter
        jupyter-notebook
        kubectl
        less
        libmnl
        libreoffice-fresh
        libtool
        links
        linux
        linux-firmware
        linux-headers
        logrotate
        lolcat
        lsof
        lvm2
        m4
        make
        man-db
        man-pages
        mdadm
        meld
        mesa
        mtr
        ncdu
        ncurses
        dialog
        neofetch
        netctl
        wireless_tools
        networkmanager
        network-manager-applet
        networkmanager-openconnect
        networkmanager-pptp
        nitrogen
        nmap
        nm-connection-editor
        noto-fonts
        noto-fonts-emoji
        noto-fonts-extra
        npm
        ntfs-3g
        obs-studio
        openconnect
        openssh
        otf-font-awesome
        pacman-contrib
        pam
        pamixer
        pandoc
        pango
        parallel
        parted
        patch
        pavucontrol
        pdftk
        perl
        php
        picom
        pkgconf
        pkgfile
        playerctl
        powerline-fonts
        protobuf
        bluez
        bluez-utils
        bluez-tools
        pulseaudio
        pulseaudio-alsa
        pulseaudio-bluetooth
        python
        python2
        python-pandas
        python-pillow
        python-pip
        python-pyqt5
        qt5-quickcontrols
        qt5-sensors
        qt5-webkit
        ranger
        rapidjson
        reiserfsprogs
        rsync
        sbcl
        scrot
        shadow
        shellcheck
        s-nail
        sof-firmware
        staticcheck
        sudo
        sysfsutils
        r
        tcl
        terraform
        texinfo
        thunar
        totem
        traceroute
        transmission-gtk
	transmission-cli
        tree
        ttf-font-awesome
        ttf-inconsolata
        unrar
        unzip
        upx
        usbutils
        util-linux
        vi
        vim
        vlc
        vulkan-intel
        wget
        which
        woff2
        xclip
        xdotool
        xf86-input-libinput
        xf86-video-fbdev
        xf86-video-intel
        xf86-video-vesa
        xf86-video-vmware
        xfce4-screenshooter
        xorg-fonts-100dpi
        xorg-fonts-75dpi
        xorg-fonts-alias-100dpi
        xorg-fonts-alias-75dpi
        xorg-fonts-encodings
        xorg-font-util
        xorg-mkfontscale
        xorgproto
        xorg-server
        xorg-setxkbmap
        xorg-xbacklight
        xorg-xev
        xorg-xhost
        xorg-xinit
        xorg-xkill
        xorg-xrandr
        xorg-xset
        xsel
        yarn
        yq
        zathura
        zathura-pdf-mupdf
        zenity
        zip
    )

    cp -a "$rootdir/files-base/"* "$pkgdir"
}
