#!/bin/bash

cd /home/duzas

lines=0
while [ "$lines" = "0" ]; do
	dialog --title "No wifi networks found" --backtitle "Unable to find wifi networks" --yesno "Scan again?" 0 0
	if [ "$?" -ne "0" ]; then
		exit 1
	fi

	clear
	echo "Scanning wifi networks..."
	sleep 1
	
	lines=$(nmcli -t device wifi list | wc -l)
done

eval "$(echo dialog --stdout --radiolist "\"Connect to a network\"" 0 0 0 $(nmcli -t device wifi list | awk -F ":" '{print "\"" $8 "\" \"" $12 "% " $14 "\" off"}')) > /tmp/dialogout.txt"
wifipwd=$(dialog --stdout --title "Connecting to $(cat /tmp/dialogout.txt)" --clear --passwordbox "Enter wifi password" 0 0)

nmcli device wifi connect "$(cat /tmp/dialogout.txt)" password "$wifipwd"


# uncommenting setting that makes pacman download 5 packages at a time
sudo sed -ri "/Parallel/s/^#//g" /etc/pacman.conf


sudo pacman -Syy
sudo pacman -S archlinux-keyring --noconfirm

# Downloading dotfiles and tools
git clone https://github.com/moretticb/linuxStuff.git
~/linuxStuff/install.sh


# Downloading collection of wallpapers
git clone https://gitlab.com/dwt1/wallpapers.git


# Installing bash-it
git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
~/.bash_it/install.sh 
#changing bash-it theme
sed -i "s/bobby/barbuk/g" ~/.bashrc



# Installing yaourt
# https://ostechnix.com/install-yaourt-arch-linux/
# https://nanxiao.me/en/fix-error-while-loading-shared-libraries-libalpm-so-10-on-archlinux/
git clone https://aur.archlinux.org/package-query.git
cd package-query/
makepkg -si --noconfirm
cd ..

git clone https://aur.archlinux.org/yaourt.git
cd yaourt/
makepkg -si --noconfirm
cd ..

sudo rm -dR yaourt/ package-query/




# Installing font with Powerline symbols for i3blocks bar
wget https://raw.githubusercontent.com/ryanoasis/powerline-extra-symbols/master/patched-fonts/DroidSansMonoForPowerlinePlusNerdFileTypesMono.otf
sudo mkdir -p /usr/share/fonts/OTF
sudo mv ./DroidSansMonoForPowerlinePlusNerdFileTypesMono.otf /usr/share/fonts/OTF/
sudo fc-cache -fv



# installing AUR packages
packages=(
	termite
	masterpdfeditor-free
	nerd-fonts-jetbrains-mono
	ttf-ms-fonts
)

for pkg in ${packages[@]}; do
	echo "Installing $pkg"
	yaourt -S $pkg --noconfirm
done





