#!/bin/bash

cd /home/duzas

eval "$(echo dialog --stdout --radiolist "\"Connect to a network\"" 0 0 0 $(nmcli device wifi list | awk -F" {2,}" '{print "\"" $3 "\"" " \"" $8,$9 "\"" " off"}')) > /tmp/dialogout.txt"
wifipwd=$(dialog --stdout --title "Connecting to $(cat /tmp/dialogout.txt)" --clear --passwordbox "Enter wifi password" 0 0)

nmcli device wifi connect "$(cat /tmp/dialogout.txt)" password "$wifipwd"



sudo pacman -Syy
sudo pacman -S archlinux-keyring

# Downloading dotfiles and tools
git clone https://github.com/moretticb/linuxStuff.git
~/linuxStuff/install.sh


# Downloading collection of wallpapers
git clone https://gitlab.com/dwt1/wallpapers.git


# Installing bash-it
git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
~/.bash_it/install.sh 
#changing bash-it theme
sed -i "s/bobby/barbuk/g" ~/.bashrc



# Installing yaourt
# https://ostechnix.com/install-yaourt-arch-linux/
# https://nanxiao.me/en/fix-error-while-loading-shared-libraries-libalpm-so-10-on-archlinux/
git clone https://aur.archlinux.org/package-query.git
cd package-query/
makepkg -si --noconfirm
cd ..

git clone https://aur.archlinux.org/yaourt.git
cd yaourt/
makepkg -si --noconfirm
cd ..

sudo rm -dR yaourt/ package-query/




# Installing font with Powerline symbols for i3blocks bar
wget https://raw.githubusercontent.com/ryanoasis/powerline-extra-symbols/master/patched-fonts/DroidSansMonoForPowerlinePlusNerdFileTypesMono.otf
sudo mkdir -p /usr/share/fonts/OTF
sudo mv ./DroidSansMonoForPowerlinePlusNerdFileTypesMono.otf /usr/share/fonts/OTF/
sudo fc-cache -fv



# installing AUR packages
packages=(
	termite
	masterpdfeditor-free
	nerd-fonts-jetbrains-mono
	ttf-ms-fonts
	wine-stable
)

for pkg in ${packages[@]}; do
	echo "Installing $pkg"
	yaourt -S $pkg --noconfirm
done





